permissions for new role for deployer
dominodatalab/terraform-aws-eks pull request #180
Opened 2023-11-24 17:47 UTC by ddl-juan-cistaro

2023-12-11 17:16 UTC, miguelhar requested changes

2023-12-11 17:16 UTC, miguelhar commented on modules/iam-bootstrap/bootstrap-2.json
> +      "Resource": "*"
can we gate resources to specific deploy id? Also keep in mind `iam_bootstrap`   is for deployment infra only.

2023-12-11 17:16 UTC, miguelhar commented on modules/iam-bootstrap/bootstrap-2.json
> +      "Resource": "*"
gate?

2023-12-11 17:16 UTC, miguelhar commented on modules/iam-bootstrap/bootstrap-2.json
> +      "Resource": "*"
gate?

2023-12-11 17:16 UTC, miguelhar commented
Needs description on PR

2023-12-12 13:53 UTC, ddl-juan-cistaro commented on modules/infra/submodules/cost-usage-report/lambda.tf
> +    from_port   = 0
We are restricting this to allow inbound and outbound traffic only from the security group is that not enough?

2023-12-12 13:54 UTC, ddl-juan-cistaro commented on modules/iam-bootstrap/main.tf
> +  iam_policy_paths = length(var.iam_policy_paths) == 0 ? ["${path.module}/bootstrap-0.json", "${path.module}/bootstrap-1.json", "${path.module}/bootstrap-2.json"] : var.iam_policy_paths
When I was doing some testing the other day I hit the limit, but after that I refactored a little, so I will check if we can stay with only two files

2023-12-12 15:17 UTC, miguelhar commented on modules/infra/submodules/cost-usage-report/lambda.tf
> +    from_port   = 0
This is saying that the lambda can take any traffic and go anywhere.

2023-12-12 15:50 UTC, ddl-juan-cistaro commented on modules/infra/submodules/cost-usage-report/lambda.tf
> +    from_port   = 0
the `self        = true` assigns itself to the boundary. Here is an example of the result of this config:
![Screenshot 2023-12-12 at 12 49 44](https://github.com/dominodatalab/terraform-aws-eks/assets/138030302/6cbc1da9-fa05-423c-aad9-f735df725516)

2023-12-13 18:46 UTC, ddl-olsonJD reviewed
nitpick

2023-12-13 18:46 UTC, ddl-olsonJD commented on modules/iam-bootstrap/bootstrap-1.json
> +}
add new line

2023-12-13 18:46 UTC, ddl-olsonJD commented on modules/iam-bootstrap/bootstrap-2.json
> +}
nl

2023-12-14 20:57 UTC, miguelhar commented
Looks good, we need to fix this warning

```
Warning: Redundant empty provider block
│
│   on ../../../../modules/infra/submodules/cost-usage-report/main.tf line 60:
│   60: provider "aws" { alias = "us-east-1" }
│
│ Earlier versions of Terraform used empty provider blocks ("proxy provider configurations") for child modules to declare their need to be passed a provider configuration by their callers. That approach was ambiguous and is now deprecated.
│
│ If you control this module, you can migrate to the new declaration syntax by removing all of the empty provider "aws" blocks and then adding or updating an entry like the following to the required_providers block of module.infra.module.cost_usage_report:
│     aws = {
│       source = "hashicorp/aws"
│       configuration_aliases = [
│         aws.us-east-1,
│       ]
│     }
```

2023-12-14 21:52 UTC, ddl-olsonJD reviewed
Also, let's change the variable name
provision_resources => provision_cost_usage_report?

2023-12-15 15:19 UTC, miguelhar reviewed
Are we testing `domino_cur.provision_cost_usage_report = true` in `examples/tfvars`

2023-12-15 15:19 UTC, miguelhar commented on modules/iam-bootstrap/bootstrap-1.json
> +        "arn:${partition}:backup:*:${account_id}:backup-plan:*",
could we restrict to `backup-plan:${deploy_id}*` ?
same for recovery-point

2023-12-15 19:04 UTC, miguelhar approved these changes

2023-12-15 19:06 UTC, merged